name: Go

on:
  push:
    branches: [ master ]
    tags:
      - 'v*'
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      
    - name: Build
      run: go build -v .

    - name: Test
      run: go test -v .
      
    - name: Publish
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        go get github.com/mitchellh/gox
        gox -arch="386 amd64" -os="windows linux darwin" ./cmd/vault-plugin-database-eventstoredb/.
        find . -type f -name "vault-plugin-database-eventstoredb_*" -exec gzip \{\} \;

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        files: '*.gz'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
